apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-ms-deployment
  labels:
    app: user-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-ms
  template:
    metadata:
      labels:
        app: user-ms 
    spec:
      containers:
      - name: nodeserver
        image: imrseba/user-ms:latest
        ports:
        - containerPort: 3000
