apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-ms-deployment
  labels:
    app: user-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-ms
  template:
    metadata:
      labels:
        app: user-ms 
    spec:
      containers:
      - name: nodeserver
        image: imrseba/ms-user:latest
        ports:
        - containerPort: 3000

apiVersion: v1
kind: Service
metadata:
  name: userms-service
spec:
  selector:
    app: user-ms
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110
