apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms-user
  template:
    metadata:
      labels:
        app: ms-user
    spec:
      containers:
      - name: ms-user
        image: imrseba/ms-user:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ms-user-service
spec:
  selector:
    app: ms-user
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
