apiVersion: v1
kind: Service
metadata:
  name: userms-service
spec:
  selector:
    app: user-ms
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110
